// DO NOT EDIT THIS FILE!
// This is an example of what your supabase-admin-config.js should look like.
// Follow the instructions in supabase-admin-config.js to set it up locally.

const SUPABASE_ADMIN_URL = 'https://your-project-url.supabase.co';
const SUPABASE_SERVICE_KEY = 'YOUR_SECRET_SERVICE_ROLE_KEY_HERE';

if (window.supabase) {
    window.supabaseAdmin = window.supabase.createClient(SUPABASE_ADMIN_URL, SUPABASE_SERVICE_KEY);
    console.log("Admin Supabase Client Initialized (service_role).");
} else {
    console.error("Admin config: Supabase library not loaded yet.");
}
